/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as DesejosRouteImport } from './routes/desejos'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesejosRoute = DesejosRouteImport.update({
  id: '/desejos',
  path: '/desejos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrentesRoute = RecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/desejos': typeof DesejosRoute
  '/despesas': typeof DespesasRoute
  '/financas': typeof FinancasRoute
  '/login': typeof LoginRoute
  '/recorrentes': typeof RecorrentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/desejos': typeof DesejosRoute
  '/despesas': typeof DespesasRoute
  '/financas': typeof FinancasRoute
  '/login': typeof LoginRoute
  '/recorrentes': typeof RecorrentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/desejos': typeof DesejosRoute
  '/despesas': typeof DespesasRoute
  '/financas': typeof FinancasRoute
  '/login': typeof LoginRoute
  '/recorrentes': typeof RecorrentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comprar'
    | '/desejos'
    | '/despesas'
    | '/financas'
    | '/login'
    | '/recorrentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comprar'
    | '/desejos'
    | '/despesas'
    | '/financas'
    | '/login'
    | '/recorrentes'
  id:
    | '__root__'
    | '/'
    | '/comprar'
    | '/desejos'
    | '/despesas'
    | '/financas'
    | '/login'
    | '/recorrentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprarRoute: typeof ComprarRoute
  DesejosRoute: typeof DesejosRoute
  DespesasRoute: typeof DespesasRoute
  FinancasRoute: typeof FinancasRoute
  LoginRoute: typeof LoginRoute
  RecorrentesRoute: typeof RecorrentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desejos': {
      id: '/desejos'
      path: '/desejos'
      fullPath: '/desejos'
      preLoaderRoute: typeof DesejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrentes': {
      id: '/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof RecorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprarRoute: ComprarRoute,
  DesejosRoute: DesejosRoute,
  DespesasRoute: DespesasRoute,
  FinancasRoute: FinancasRoute,
  LoginRoute: LoginRoute,
  RecorrentesRoute: RecorrentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
